### PR TITLE
refactor: use new decky API

### PR DESCRIPTION
**Pull request by eXhumer**
* use new decky API
* fix issue with `cloud_enabled` not being available available with app overview

### CODE REVIEW

**Comment by mcarlucci** [comment]
Hi @eXhumer, thanks for your PR and hard work! 

I am traveling currently, so I don’t have access to my dev laptop and steam deck. I will review and test on Monday.

**Comment by eXhumer** [comment]
This fixes #14, so close that alongside if this gets merged.

**Comment by mcarlucci** [comment]
LGTM :shipit:

**Comment by mcarlucci** [comment]
@eXhumer Opened a [PR](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/706) to get this into testing. If everything checks out, 1.4.0 should be available soon. 

Thanks again for your contributions 🙌

**Pull request merged**
